name: Lint

on:
  push:
    branches:
      - master
      - lint
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: 'snapshot'

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      - name: Resolve dependency
        run: eask install-deps --dev

      - name: Run Indentation Lint
        run: |
          find . -name "*.el" ! -path "./.eask/*" \
          | xargs -t -I^ eask emacs -q --batch ^ --eval "\
            (let ((require-final-newline t)) \
              (require 'flycheck) \
              (eval-buffer) \
              (untabify (point-min) (point-max)) \
              (indent-region (point-min) (point-max)) \
              (save-buffer))"
          
          CHANGED=$(git diff --name-only)
          if [ -n "$CHANGED" ]; then
            echo "The following files have indentation changes:"
            echo "$CHANGED"
            exit 1
          fi
