name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v19

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: ans,ine,inh,isnt

  emacs-indentation-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jcs090218/setup-emacs@3586c34483bee442d1293c9a428fa3da44421509
        with:
          version: snapshot

      - uses: emacs-eask/setup-eask@cc250315b6a3177fa27dbb5bb6a2a9d9b90b2ef7
        with:
          version: snapshot

      - run: eask install-deps --dev

      - name: Check indentation
        run: |
          find . -name "*.el" ! -path "./.eask/*" \
          | xargs -t -I^ eask emacs -q --batch ^ --eval "\
            (require 'editorconfig)
            (setq editorconfig-lisp-use-default-indent 2)
            (editorconfig-mode t)

            (untabify (point-min) (point-max))
            (indent-region (point-min) (point-max))
            (save-buffer)"

          git diff

          CHANGED=$(git diff --name-only | sort)
          if [ -n "$CHANGED" ]; then
            for file in $CHANGED; do
              echo "::warning file=$file::$file needs indentation fix"
            done
            exit 1
          fi

          echo -e "\033[0;32mNo files need indentation fix\033[0m"
